### ISSUE TITLE
NodeJS v0.12 npm install errors

### ISSUE THREAD

**Issue by gdbtek** [normanjoyner/chef-api#20]
`npm install` with the new NodeJS v0.12 will have compiler errors

```
make: *** [Release/obj.target/ursaNative/src/ursaNative.o] Error 1
make: Leaving directory `/tmp/chef-api/node_modules/ursa/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.13.0-45-generic
gyp ERR! command "node" "/opt/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /tmp/chef-api/node_modules/ursa
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.13.0-45-generic
npm ERR! argv "/opt/node/bin/node" "/opt/node/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! ursa@0.8.0 install: `node-gyp configure build && node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ursa@0.8.0 install script 'node-gyp configure build && node install.js'.
npm ERR! This is most likely a problem with the ursa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build && node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ursa
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/chef-api/npm-debug.log
```

**Comment by gdbtek** [comment]
REF Issue from URSA: https://github.com/NodePrime/ursa/issues/73
