### ISSUE TITLE
Timeout error when attempting to access private chef

### ISSUE THREAD

**Issue by paul42** [normanjoyner/chef-api#22]
I'm not certain if I'm doing this right, I've opened the fw's between my workstation and the chef instance, but I'm running the latest chef (v12)

when I attempt to run the code you provided in the example I get this error:

C:\code\chef-helper.js:17
        throw err;
              ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)

**Comment by normanjoyner** [comment]
If you are still using this library / running into issues please provide the options you are passing to configure chef-api.
